import type { Category, Product, StoreSettings, StorefrontPayload } from '../types'
import { categoryImageMap } from './constants'

export const fallbackCategories: Category[] = [
  {
    id: 'cat-semipermanentes',
    slug: 'semipermanentes',
    name: 'Semipermanentes',
    description: 'Colores y lineas de alta rotacion para servicio diario.',
    imageUrl: categoryImageMap.semipermanentes,
    site: 'anahinails',
    subcategories: ['City Girl', 'Navi'],
  },
  {
    id: 'cat-polygel',
    slug: 'polygel',
    name: 'Polygel',
    description: 'Lineas y tonos para construccion y refuerzo profesional.',
    imageUrl: categoryImageMap.polygel,
    site: 'anahinails',
    subcategories: ['Construccion', 'Easy Gel', 'City Girl'],
  },
  {
    id: 'cat-decoracion',
    slug: 'decoracion',
    name: 'Decoracion y Nail Art',
    description: 'Stickers, pigmentos, piedras y detalles para elevar el ticket.',
    imageUrl: categoryImageMap.decoracion,
    site: 'anahinails',
    subcategories: ['Bases', 'Cat Eye', 'Apliques'],
  },
  {
    id: 'cat-soft-gel',
    slug: 'soft-gel',
    name: 'Soft Gel',
    description: 'Tips y soluciones para sets rapidos, prolijos y premium.',
    imageUrl: categoryImageMap['soft-gel'],
    site: 'anahinails',
    subcategories: ['Kits'],
  },
  {
    id: 'cat-herramientas',
    slug: 'cabinas-y-herramientas',
    name: 'Cabinas y Herramientas',
    description: 'Cabinas, tornos, fresas y accesorios clave para profesionales.',
    imageUrl: categoryImageMap['cabinas-y-herramientas'],
    site: 'anahinails',
    subcategories: ['Cabinas', 'Extractores'],
  },
  {
    id: 'cat-pinceles',
    slug: 'pinceles-y-accesorios',
    name: 'Pinceles y Accesorios',
    description: 'Complementos de trabajo para detalle, precision y terminacion.',
    imageUrl: categoryImageMap['pinceles-y-accesorios'],
    site: 'anahinails',
    subcategories: [],
  },
  {
    id: 'cat-ws-buzos',
    slug: 'buzos',
    name: 'Buzos',
    description: 'Buzos premium a pedido y de identidad visual propia.',
    imageUrl: '/wild-spirit-logo.jpeg',
    site: 'wildspirit',
    subcategories: ['Oversize'],
  },
  {
    id: 'cat-ws-remeras',
    slug: 'remeras',
    name: 'Remeras',
    description: 'Remeras boxy y oversized para diseño exclusivo.',
    imageUrl: '/wild-spirit-logo.jpeg',
    site: 'wildspirit',
    subcategories: ['Boxy'],
  },
]

export const fallbackProducts: Product[] = [
  {
    id: 'prod-01',
    slug: 'city-girl-semipermanente-40-10ml',
    sku: 'AND-SP-040',
    name: 'City Girl - Semipermanente - 40 - 10ml.',
    description: 'Esmalte semipermanente de alta rotacion para servicios rapidos, prolijos y de brillo intenso.',
    shortDescription: 'Semipermanente City Girl de 10ml.',
    price: 4900,
    compareAtPrice: null,
    stock: 24,
    featured: true,
    badges: ['best-seller'],
    imageUrls: [categoryImageMap.semipermanentes],
    categoryId: 'cat-semipermanentes',
    categoryName: 'Semipermanentes',
    site: 'anahinails',
    subcategory: 'City Girl',
    variants: [
      {
        id: 'var-fb-01',
        name: 'Tono 40',
        color: 'Cherry',
        imageUrl: categoryImageMap.semipermanentes,
        stock: 12,
      },
    ],
  },
  {
    id: 'prod-02',
    slug: 'base-mineral',
    sku: 'AND-BM-010',
    name: 'Base Mineral',
    description: 'Base formulada con calcio, hierro y magnesio, ideal para uñas debilitadas y servicio de cuidado.',
    shortDescription: 'Base fortalecedora vegana y cruelty free.',
    price: 14000,
    compareAtPrice: null,
    stock: 10,
    featured: true,
    badges: ['new'],
    imageUrls: [categoryImageMap.decoracion],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
    site: 'anahinails',
    subcategory: 'Bases',
    variants: [],
  },
  {
    id: 'prod-03',
    slug: 'polygel-city-girl-rose-city-girl-01-30ml',
    sku: 'AND-PG-001',
    name: 'Polygel -City Girl- Rose City Girl- (01) 30ml.',
    description: 'Polygel para construccion con tono comercial y presentacion de 30ml para uso profesional.',
    shortDescription: 'Polygel City Girl 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 12,
    featured: true,
    badges: ['best-seller'],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
    site: 'anahinails',
    subcategory: 'Construccion',
    variants: [],
  },
  {
    id: 'prod-03b',
    slug: 'polygel-city-girl-rose-crystal-10-30ml',
    sku: 'AND-PG-010',
    name: 'Polygel -City Girl- Rose Crystal - (10) 30ml.',
    description: 'Polygel City Girl de 30ml orientado a construcción profesional con tono de alta salida.',
    shortDescription: 'Polygel City Girl Rose Crystal 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 12,
    featured: false,
    badges: ['new'],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
    site: 'anahinails',
    subcategory: 'City Girl',
    variants: [],
  },
  {
    id: 'prod-03c',
    slug: 'polygel-city-girl-natural-beauty-07-30ml',
    sku: 'AND-PG-007',
    name: 'Polygel -City Girl- Natural Beauty - (07) 30ml.',
    description: 'Tono natural para construcción y refuerzo con salida frecuente en servicios de salón.',
    shortDescription: 'Polygel City Girl Natural Beauty 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 9,
    featured: false,
    badges: [],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
    site: 'anahinails',
    subcategory: 'City Girl',
    variants: [],
  },
  {
    id: 'prod-03d',
    slug: 'polygel-city-girl-natural-beige-15-30ml',
    sku: 'AND-PG-015',
    name: 'Polygel -City Girl- Natural Beige - (15) 30ml.',
    description: 'Polygel en tono natural beige para mesa de trabajo y armado de sets comerciales.',
    shortDescription: 'Polygel City Girl Natural Beige 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 7,
    featured: false,
    badges: [],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
    site: 'anahinails',
    subcategory: 'City Girl',
    variants: [],
  },
  {
    id: 'prod-04',
    slug: 'polygel-easy-gel-cover-pink-60g',
    sku: 'AND-PG-060',
    name: 'Polygel-Easy Gel -Cover Pink 60g.',
    description: 'Presentacion de 60g para servicio intensivo, ideal para mesa de trabajo con buena rotacion.',
    shortDescription: 'Polygel Easy Gel Cover Pink 60g.',
    price: 15600,
    compareAtPrice: null,
    stock: 18,
    featured: true,
    badges: ['new'],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
    site: 'anahinails',
    subcategory: 'Easy Gel',
    variants: [],
  },
  {
    id: 'prod-05',
    slug: '2-marfil-cat-eye-city-girl-7-ml',
    sku: 'AND-CE-002',
    name: '2 MARFIL - CAT EYE CITY GIRL 7 ML.',
    description: 'Cat eye profesional con descuento activo y alta salida por tendencia y acabado visual.',
    shortDescription: 'Cat eye City Girl 7 ml en oferta.',
    price: 5350,
    compareAtPrice: 5700,
    stock: 8,
    featured: true,
    badges: ['sale', 'best-seller'],
    imageUrls: [categoryImageMap.decoracion],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
    site: 'anahinails',
    subcategory: 'Cat Eye',
    variants: [],
  },
  {
    id: 'prod-05b',
    slug: '86-negro-cat-eye-city-girl-7-ml',
    sku: 'AND-CE-086',
    name: '86 - NEGRO CAT EYE CITY GIRL 7 ML.',
    description: 'Cat eye negro de City Girl con precio promo y muy buena rotación en la línea.',
    shortDescription: 'Cat eye negro City Girl 7 ml.',
    price: 5350,
    compareAtPrice: 5700,
    stock: 6,
    featured: true,
    badges: ['sale'],
    imageUrls: [categoryImageMap.decoracion],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
    site: 'anahinails',
    subcategory: 'Cat Eye',
    variants: [],
  },
  {
    id: 'prod-05c',
    slug: '007-navi-color',
    sku: 'AND-NAVI-007',
    name: '007 - Navi color',
    description: 'Tono de esmalte Navi con descuento activo y buena salida en destacados.',
    shortDescription: 'Esmalte Navi color en oferta.',
    price: 5350,
    compareAtPrice: 5700,
    stock: 11,
    featured: true,
    badges: ['sale', 'best-seller'],
    imageUrls: [categoryImageMap.semipermanentes],
    categoryId: 'cat-semipermanentes',
    categoryName: 'Semipermanentes',
    site: 'anahinails',
    subcategory: 'Navi',
    variants: [],
  },
  {
    id: 'prod-08',
    slug: 'cabina-uv-led-diamond-x',
    sku: 'AND-CAB-008',
    name: 'Cabina UV LED Diamond X',
    description: 'Cabina profesional UV LED para servicio continuo en mesa de trabajo o salon.',
    shortDescription: 'Cabina profesional UV/LED.',
    price: 45900,
    compareAtPrice: 51900,
    stock: 8,
    featured: true,
    badges: ['sale'],
    imageUrls: [categoryImageMap['cabinas-y-herramientas']],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
    site: 'anahinails',
    subcategory: 'Cabinas',
    variants: [],
  },
  {
    id: 'prod-08b',
    slug: 'cabina-uv-led-54w-duga',
    sku: 'AND-CAB-054',
    name: 'CABINA UV/LED 54W - DUGA',
    description: 'Cabina UV/LED de 54W con precio promocional para servicio profesional.',
    shortDescription: 'Cabina DUGA 54W en oferta.',
    price: 46000,
    compareAtPrice: 64900,
    stock: 5,
    featured: true,
    badges: ['sale'],
    imageUrls: [categoryImageMap['cabinas-y-herramientas']],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
    site: 'anahinails',
    subcategory: 'Cabinas',
    variants: [],
  },
  {
    id: 'prod-08c',
    slug: 'cabina-uv-led-75w-duga-inalambrica',
    sku: 'AND-CAB-075',
    name: 'CABINA UV/LED 75 W DUGA INALAMBRICA',
    description: 'Cabina inalámbrica de 75W para mesa de trabajo exigente y servicios de alta rotación.',
    shortDescription: 'Cabina DUGA inalámbrica 75W.',
    price: 139000,
    compareAtPrice: 150000,
    stock: 4,
    featured: false,
    badges: ['sale'],
    imageUrls: [categoryImageMap['cabinas-y-herramientas']],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
    site: 'anahinails',
    subcategory: 'Cabinas',
    variants: [],
  },
  {
    id: 'prod-08d',
    slug: 'extractor-cherimoya',
    sku: 'AND-EXT-001',
    name: 'Extractor CHERIMOYA',
    description: 'Extractor profesional para mesa de manicura con ticket alto y salida comercial.',
    shortDescription: 'Extractor profesional Cherimoya.',
    price: 85000,
    compareAtPrice: null,
    stock: 3,
    featured: false,
    badges: ['best-seller'],
    imageUrls: [categoryImageMap['cabinas-y-herramientas']],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
    site: 'anahinails',
    subcategory: 'Extractores',
    variants: [],
  },
  {
    id: 'prod-ws-fb-01',
    slug: 'wild-spirit-buzo-signature',
    sku: 'WS-BZ-FB-01',
    name: 'Buzo Signature Wild Spirit',
    description: 'Buzo de diseño exclusivo, producido a pedido y con identidad visual marcada.',
    shortDescription: 'Buzo premium a pedido.',
    price: 48900,
    compareAtPrice: null,
    stock: 11,
    featured: true,
    badges: ['best-seller'],
    imageUrls: ['/wild-spirit-logo.jpeg'],
    categoryId: 'cat-ws-buzos',
    categoryName: 'Buzos',
    site: 'wildspirit',
    subcategory: 'Oversize',
    variants: [
      { id: 'prod-ws-fb-01-black', name: 'Negro', color: 'Negro', imageUrl: '/wild-spirit-logo.jpeg', stock: 5 },
      { id: 'prod-ws-fb-01-cream', name: 'Cream', color: 'Cream', imageUrl: '/wild-spirit-logo.jpeg', stock: 6 },
    ],
  },
  {
    id: 'prod-ws-fb-02',
    slug: 'wild-spirit-remera-essence',
    sku: 'WS-RM-FB-02',
    name: 'Remera Essence Wild Spirit',
    description: 'Remera premium de algodón con diseño exclusivo y confección a pedido.',
    shortDescription: 'Remera boxy a pedido.',
    price: 28900,
    compareAtPrice: null,
    stock: 14,
    featured: true,
    badges: ['new'],
    imageUrls: ['/wild-spirit-logo.jpeg'],
    categoryId: 'cat-ws-remeras',
    categoryName: 'Remeras',
    site: 'wildspirit',
    subcategory: 'Boxy',
    variants: [
      { id: 'prod-ws-fb-02-white', name: 'Blanca', color: 'Blanco', imageUrl: '/wild-spirit-logo.jpeg', stock: 7 },
      { id: 'prod-ws-fb-02-stone', name: 'Stone', color: 'Stone', imageUrl: '/wild-spirit-logo.jpeg', stock: 7 },
    ],
  },
]

export const fallbackStorefront: StorefrontPayload = {
  categories: fallbackCategories,
  featuredProducts: fallbackProducts.filter((item) => item.site === 'anahinails'),
  bestSellers: fallbackProducts.filter((item) => item.badges.includes('best-seller')).slice(0, 4),
  newArrivals: fallbackProducts.filter((item) => item.badges.includes('new')).slice(0, 4),
}

export const fallbackSettings: StoreSettings = {
  id: 'main',
  standardShippingLabel: 'Envío a domicilio',
  standardShippingCost: 0,
  branchShippingEnabled: true,
  branchShippingLabel: 'Envío a sucursal',
  branchShippingCost: 0,
  freeShippingEnabled: true,
  freeShippingThreshold: 250000,
}
