import type { Category, Product, StorefrontPayload } from '../types'
import { categoryImageMap } from './constants'

export const fallbackCategories: Category[] = [
  {
    id: 'cat-semipermanentes',
    slug: 'semipermanentes',
    name: 'Semipermanentes',
    description: 'Colores y lineas de alta rotacion para servicio diario.',
    imageUrl: categoryImageMap.semipermanentes,
  },
  {
    id: 'cat-polygel',
    slug: 'polygel',
    name: 'Polygel',
    description: 'Lineas y tonos para construccion y refuerzo profesional.',
    imageUrl: categoryImageMap.polygel,
  },
  {
    id: 'cat-decoracion',
    slug: 'decoracion',
    name: 'Decoracion y Nail Art',
    description: 'Stickers, pigmentos, piedras y detalles para elevar el ticket.',
    imageUrl: categoryImageMap.decoracion,
  },
  {
    id: 'cat-soft-gel',
    slug: 'soft-gel',
    name: 'Soft Gel',
    description: 'Tips y soluciones para sets rapidos, prolijos y premium.',
    imageUrl: categoryImageMap['soft-gel'],
  },
  {
    id: 'cat-herramientas',
    slug: 'cabinas-y-herramientas',
    name: 'Cabinas y Herramientas',
    description: 'Cabinas, tornos, fresas y accesorios clave para profesionales.',
    imageUrl: categoryImageMap['cabinas-y-herramientas'],
  },
  {
    id: 'cat-pinceles',
    slug: 'pinceles-y-accesorios',
    name: 'Pinceles y Accesorios',
    description: 'Complementos de trabajo para detalle, precision y terminacion.',
    imageUrl: categoryImageMap['pinceles-y-accesorios'],
  },
]

export const fallbackProducts: Product[] = [
  {
    id: 'prod-01',
    slug: 'city-girl-semipermanente-40-10ml',
    sku: 'AND-SP-040',
    name: 'City Girl - Semipermanente - 40 - 10ml.',
    description: 'Esmalte semipermanente de alta rotacion para servicios rapidos, prolijos y de brillo intenso.',
    shortDescription: 'Semipermanente City Girl de 10ml.',
    price: 4900,
    compareAtPrice: null,
    stock: 24,
    featured: true,
    badges: ['best-seller'],
    imageUrls: [categoryImageMap.semipermanentes],
    categoryId: 'cat-semipermanentes',
    categoryName: 'Semipermanentes',
  },
  {
    id: 'prod-02',
    slug: 'base-mineral',
    sku: 'AND-BM-010',
    name: 'Base Mineral',
    description: 'Base formulada con calcio, hierro y magnesio, ideal para uñas debilitadas y servicio de cuidado.',
    shortDescription: 'Base fortalecedora vegana y cruelty free.',
    price: 14000,
    compareAtPrice: null,
    stock: 10,
    featured: true,
    badges: ['new'],
    imageUrls: [categoryImageMap.decoracion],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
  },
  {
    id: 'prod-03',
    slug: 'polygel-city-girl-rose-city-girl-01-30ml',
    sku: 'AND-PG-001',
    name: 'Polygel -City Girl- Rose City Girl- (01) 30ml.',
    description: 'Polygel para construccion con tono comercial y presentacion de 30ml para uso profesional.',
    shortDescription: 'Polygel City Girl 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 12,
    featured: true,
    badges: ['best-seller'],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
  },
  {
    id: 'prod-03b',
    slug: 'polygel-city-girl-rose-crystal-10-30ml',
    sku: 'AND-PG-010',
    name: 'Polygel -City Girl- Rose Crystal - (10) 30ml.',
    description: 'Polygel City Girl de 30ml orientado a construcción profesional con tono de alta salida.',
    shortDescription: 'Polygel City Girl Rose Crystal 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 12,
    featured: false,
    badges: ['new'],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
  },
  {
    id: 'prod-03c',
    slug: 'polygel-city-girl-natural-beauty-07-30ml',
    sku: 'AND-PG-007',
    name: 'Polygel -City Girl- Natural Beauty - (07) 30ml.',
    description: 'Tono natural para construcción y refuerzo con salida frecuente en servicios de salón.',
    shortDescription: 'Polygel City Girl Natural Beauty 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 9,
    featured: false,
    badges: [],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
  },
  {
    id: 'prod-03d',
    slug: 'polygel-city-girl-natural-beige-15-30ml',
    sku: 'AND-PG-015',
    name: 'Polygel -City Girl- Natural Beige - (15) 30ml.',
    description: 'Polygel en tono natural beige para mesa de trabajo y armado de sets comerciales.',
    shortDescription: 'Polygel City Girl Natural Beige 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 7,
    featured: false,
    badges: [],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
  },
  {
    id: 'prod-04',
    slug: 'polygel-easy-gel-cover-pink-60g',
    sku: 'AND-PG-060',
    name: 'Polygel-Easy Gel -Cover Pink 60g.',
    description: 'Presentacion de 60g para servicio intensivo, ideal para mesa de trabajo con buena rotacion.',
    shortDescription: 'Polygel Easy Gel Cover Pink 60g.',
    price: 15600,
    compareAtPrice: null,
    stock: 18,
    featured: true,
    badges: ['new'],
    imageUrls: [categoryImageMap.polygel],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
  },
  {
    id: 'prod-05',
    slug: '2-marfil-cat-eye-city-girl-7-ml',
    sku: 'AND-CE-002',
    name: '2 MARFIL - CAT EYE CITY GIRL 7 ML.',
    description: 'Cat eye profesional con descuento activo y alta salida por tendencia y acabado visual.',
    shortDescription: 'Cat eye City Girl 7 ml en oferta.',
    price: 5350,
    compareAtPrice: 5700,
    stock: 8,
    featured: true,
    badges: ['sale', 'best-seller'],
    imageUrls: [categoryImageMap.decoracion],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
  },
  {
    id: 'prod-05b',
    slug: '86-negro-cat-eye-city-girl-7-ml',
    sku: 'AND-CE-086',
    name: '86 - NEGRO CAT EYE CITY GIRL 7 ML.',
    description: 'Cat eye negro de City Girl con precio promo y muy buena rotación en la línea.',
    shortDescription: 'Cat eye negro City Girl 7 ml.',
    price: 5350,
    compareAtPrice: 5700,
    stock: 6,
    featured: true,
    badges: ['sale'],
    imageUrls: [categoryImageMap.decoracion],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
  },
  {
    id: 'prod-05c',
    slug: '007-navi-color',
    sku: 'AND-NAVI-007',
    name: '007 - Navi color',
    description: 'Tono de esmalte Navi con descuento activo y buena salida en destacados.',
    shortDescription: 'Esmalte Navi color en oferta.',
    price: 5350,
    compareAtPrice: 5700,
    stock: 11,
    featured: true,
    badges: ['sale', 'best-seller'],
    imageUrls: [categoryImageMap.semipermanentes],
    categoryId: 'cat-semipermanentes',
    categoryName: 'Semipermanentes',
  },
  {
    id: 'prod-08',
    slug: 'cabina-uv-led-diamond-x',
    sku: 'AND-CAB-008',
    name: 'Cabina UV LED Diamond X',
    description: 'Cabina profesional UV LED para servicio continuo en mesa de trabajo o salon.',
    shortDescription: 'Cabina profesional UV/LED.',
    price: 45900,
    compareAtPrice: 51900,
    stock: 8,
    featured: true,
    badges: ['sale'],
    imageUrls: [categoryImageMap['cabinas-y-herramientas']],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
  },
  {
    id: 'prod-08b',
    slug: 'cabina-uv-led-54w-duga',
    sku: 'AND-CAB-054',
    name: 'CABINA UV/LED 54W - DUGA',
    description: 'Cabina UV/LED de 54W con precio promocional para servicio profesional.',
    shortDescription: 'Cabina DUGA 54W en oferta.',
    price: 46000,
    compareAtPrice: 64900,
    stock: 5,
    featured: true,
    badges: ['sale'],
    imageUrls: [categoryImageMap['cabinas-y-herramientas']],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
  },
  {
    id: 'prod-08c',
    slug: 'cabina-uv-led-75w-duga-inalambrica',
    sku: 'AND-CAB-075',
    name: 'CABINA UV/LED 75 W DUGA INALAMBRICA',
    description: 'Cabina inalámbrica de 75W para mesa de trabajo exigente y servicios de alta rotación.',
    shortDescription: 'Cabina DUGA inalámbrica 75W.',
    price: 139000,
    compareAtPrice: 150000,
    stock: 4,
    featured: false,
    badges: ['sale'],
    imageUrls: [categoryImageMap['cabinas-y-herramientas']],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
  },
  {
    id: 'prod-08d',
    slug: 'extractor-cherimoya',
    sku: 'AND-EXT-001',
    name: 'Extractor CHERIMOYA',
    description: 'Extractor profesional para mesa de manicura con ticket alto y salida comercial.',
    shortDescription: 'Extractor profesional Cherimoya.',
    price: 85000,
    compareAtPrice: null,
    stock: 3,
    featured: false,
    badges: ['best-seller'],
    imageUrls: [categoryImageMap['cabinas-y-herramientas']],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
  },
]

export const fallbackStorefront: StorefrontPayload = {
  categories: fallbackCategories,
  featuredProducts: fallbackProducts,
  bestSellers: fallbackProducts.filter((item) => item.badges.includes('best-seller')).slice(0, 4),
  newArrivals: fallbackProducts.filter((item) => item.badges.includes('new')).slice(0, 4),
}
