export const seedCategories = [
  {
    id: 'cat-semipermanentes',
    slug: 'semipermanentes',
    name: 'Semipermanentes',
    description: 'Colores y lineas de alta rotacion para servicio diario.',
  },
  {
    id: 'cat-polygel',
    slug: 'polygel',
    name: 'Polygel',
    description: 'Lineas y tonos para construccion y refuerzo profesional.',
  },
  {
    id: 'cat-decoracion',
    slug: 'decoracion',
    name: 'Decoracion y Nail Art',
    description: 'Stickers, pigmentos, piedras y detalles para elevar el ticket.',
  },
  {
    id: 'cat-soft-gel',
    slug: 'soft-gel',
    name: 'Soft Gel',
    description: 'Tips y soluciones para sets rapidos, prolijos y premium.',
  },
  {
    id: 'cat-herramientas',
    slug: 'cabinas-y-herramientas',
    name: 'Cabinas y Herramientas',
    description: 'Cabinas, tornos, fresas y accesorios clave para profesionales.',
  },
  {
    id: 'cat-pinceles',
    slug: 'pinceles-y-accesorios',
    name: 'Pinceles y Accesorios',
    description: 'Complementos de trabajo para detalle, precision y terminacion.',
  },
]

export const seedProducts = [
  {
    id: 'prod-01',
    slug: 'city-girl-semipermanente-40-10ml',
    sku: 'AND-SP-040',
    name: 'City Girl - Semipermanente - 40 - 10ml.',
    description: 'Esmalte semipermanente de alta rotacion para servicios rapidos, prolijos y de brillo intenso.',
    shortDescription: 'Semipermanente City Girl de 10ml.',
    price: 4900,
    compareAtPrice: null,
    stock: 24,
    featured: true,
    badges: ['best-seller'],
    imageUrls: ['https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-semipermanentes',
    categoryName: 'Semipermanentes',
  },
  {
    id: 'prod-02',
    slug: 'city-girl-semipermanente-120-10ml',
    sku: 'AND-SP-120',
    name: 'City Girl - Semipermanente - 120 - 10ml.',
    description: 'Color semipermanente ideal para ampliar carta de tonos y sostener recompra frecuente.',
    shortDescription: 'Tono City Girl de alta salida.',
    price: 4900,
    compareAtPrice: null,
    stock: 31,
    featured: false,
    badges: ['new'],
    imageUrls: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-semipermanentes',
    categoryName: 'Semipermanentes',
  },
  {
    id: 'prod-03',
    slug: 'polygel-city-girl-rose-city-girl-01-30ml',
    sku: 'AND-PG-001',
    name: 'Polygel -City Girl- Rose City Girl- (01) 30ml.',
    description: 'Polygel para construccion con tono comercial y presentacion de 30ml para uso profesional.',
    shortDescription: 'Polygel City Girl 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 12,
    featured: true,
    badges: ['best-seller'],
    imageUrls: ['https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
  },
  {
    id: 'prod-04',
    slug: 'polygel-easy-gel-cover-pink-60g',
    sku: 'AND-PG-060',
    name: 'Polygel-Easy Gel -Cover Pink 60g.',
    description: 'Presentacion de 60g para servicio intensivo, ideal para mesa de trabajo con buena rotacion.',
    shortDescription: 'Polygel Easy Gel Cover Pink 60g.',
    price: 15600,
    compareAtPrice: null,
    stock: 18,
    featured: true,
    badges: ['new'],
    imageUrls: ['https://images.unsplash.com/photo-1607602132700-06825880252c?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
  },
  {
    id: 'prod-05',
    slug: '2-marfil-cat-eye-city-girl-7-ml',
    sku: 'AND-CE-002',
    name: '2 MARFIL - CAT EYE CITY GIRL 7 ML.',
    description: 'Cat eye profesional con descuento activo y alta salida por tendencia y acabado visual.',
    shortDescription: 'Cat eye City Girl 7 ml en oferta.',
    price: 5350,
    compareAtPrice: 5700,
    stock: 8,
    featured: true,
    badges: ['sale', 'best-seller'],
    imageUrls: ['https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
  },
  {
    id: 'prod-06',
    slug: 'base-mineral',
    sku: 'AND-BM-010',
    name: 'Base Mineral',
    description: 'Base formulada con calcio, hierro y magnesio, ideal para unas debilitadas y servicio de cuidado.',
    shortDescription: 'Base fortalecedora vegana y cruelty free.',
    price: 14000,
    compareAtPrice: null,
    stock: 10,
    featured: false,
    badges: ['new'],
    imageUrls: ['https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
  },
  {
    id: 'prod-07',
    slug: 'kit-soft-gel-nude-studio',
    sku: 'AND-SG-007',
    name: 'Kit Soft Gel Nude Studio',
    description: 'Kit orientado a servicio rapido y prolijo para sets soft gel con terminacion comercial.',
    shortDescription: 'Kit integral de soft gel.',
    price: 26900,
    compareAtPrice: 29900,
    stock: 9,
    featured: false,
    badges: ['sale'],
    imageUrls: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-soft-gel',
    categoryName: 'Soft Gel',
  },
  {
    id: 'prod-08',
    slug: 'cabina-uv-led-diamond-x',
    sku: 'AND-CAB-008',
    name: 'Cabina UV LED Diamond X',
    description: 'Cabina profesional UV LED para servicio continuo en mesa de trabajo o salon.',
    shortDescription: 'Cabina profesional UV/LED.',
    price: 45900,
    compareAtPrice: 51900,
    stock: 8,
    featured: true,
    badges: ['sale'],
    imageUrls: ['https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
  },
  {
    id: 'prod-09',
    slug: 'alas-de-angel-1-dorado',
    sku: 'AND-DEC-009',
    name: 'Alas de Angel #1 Dorado',
    description: 'Aplique decorativo para sumar detalle y valor a trabajos de nail art y sets tematicos.',
    shortDescription: 'Aplique decorativo dorado.',
    price: 3990,
    compareAtPrice: null,
    stock: 50,
    featured: false,
    badges: ['new'],
    imageUrls: ['https://images.unsplash.com/photo-1583241801126-2b72975af370?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
  },
]
