export const seedCategories = [
  {
    id: 'cat-semipermanentes',
    slug: 'semipermanentes',
    name: 'Semipermanentes',
    description: 'Colores y lineas de alta rotacion para servicio diario.',
    site: 'anahinails',
    subcategories: ['Semipermanente', 'Esmalte en gel'],
  },
  {
    id: 'cat-polygel',
    slug: 'polygel',
    name: 'Polygel',
    description: 'Lineas y tonos para construccion y refuerzo profesional.',
    site: 'anahinails',
    subcategories: ['Construccion', 'Easy Gel', 'City Girl'],
  },
  {
    id: 'cat-decoracion',
    slug: 'decoracion',
    name: 'Decoracion y Nail Art',
    description: 'Stickers, pigmentos, piedras y detalles para elevar el ticket.',
    site: 'anahinails',
    subcategories: ['Bases', 'Cat Eye', 'Apliques'],
  },
  {
    id: 'cat-soft-gel',
    slug: 'soft-gel',
    name: 'Soft Gel',
    description: 'Tips y soluciones para sets rapidos, prolijos y premium.',
    site: 'anahinails',
    subcategories: ['Kits'],
  },
  {
    id: 'cat-herramientas',
    slug: 'cabinas-y-herramientas',
    name: 'Cabinas y Herramientas',
    description: 'Cabinas, tornos, fresas y accesorios clave para profesionales.',
    site: 'anahinails',
    subcategories: ['Cabinas', 'Extractores'],
  },
  {
    id: 'cat-pinceles',
    slug: 'pinceles-y-accesorios',
    name: 'Pinceles y Accesorios',
    description: 'Complementos de trabajo para detalle, precision y terminacion.',
    site: 'anahinails',
    subcategories: [],
  },
  {
    id: 'cat-ws-buzos',
    slug: 'buzos',
    name: 'Buzos',
    description: 'Buzos a pedido con identidad propia, visual exclusiva y terminacion premium.',
    site: 'wildspirit',
    subcategories: ['Oversize'],
  },
  {
    id: 'cat-ws-remeras',
    slug: 'remeras',
    name: 'Remeras',
    description: 'Remeras personalizadas para vestir tu esencia con diseño y calidad.',
    site: 'wildspirit',
    subcategories: ['Boxy'],
  },
  {
    id: 'cat-ws-ropa',
    slug: 'ropa',
    name: 'Ropa',
    description: 'Categoria general para organizar prendas y accesorios por subcategoria.',
    site: 'wildspirit',
    subcategories: ['Accesorios', 'Buzos', 'Lentes', 'Remeras'],
  },
]

export const seedProducts = [
  {
    id: 'prod-01',
    slug: 'city-girl-semipermanente-40-10ml',
    sku: 'AND-SP-040',
    name: 'City Girl - Semipermanente - 40 - 10ml.',
    description: 'Esmalte semipermanente de alta rotacion para servicios rapidos, prolijos y de brillo intenso.',
    shortDescription: 'Semipermanente City Girl de 10ml.',
    price: 4900,
    compareAtPrice: null,
    stock: 24,
    featured: true,
    badges: ['best-seller'],
    imageUrls: ['https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-semipermanentes',
    categoryName: 'Semipermanentes',
    site: 'anahinails',
    subcategory: 'Semipermanente',
    brand: 'City Girl',
    variants: [
      {
        id: 'var-01-40',
        name: 'Tono 40',
        color: 'Bordeaux',
        imageUrl: 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=900&q=80',
        stock: 12,
      },
      {
        id: 'var-01-40b',
        name: 'Tono 40 shimmer',
        color: 'Cherry Glow',
        imageUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=80',
        stock: 12,
      },
    ],
  },
  {
    id: 'prod-02',
    slug: 'city-girl-semipermanente-120-10ml',
    sku: 'AND-SP-120',
    name: 'City Girl - Semipermanente - 120 - 10ml.',
    description: 'Color semipermanente ideal para ampliar carta de tonos y sostener recompra frecuente.',
    shortDescription: 'Tono City Girl de alta salida.',
    price: 4900,
    compareAtPrice: null,
    stock: 31,
    featured: false,
    badges: ['new'],
    imageUrls: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-semipermanentes',
    categoryName: 'Semipermanentes',
    site: 'anahinails',
    subcategory: 'Semipermanente',
    brand: 'Rimera Quince',
    variants: [],
  },
  {
    id: 'prod-03',
    slug: 'polygel-city-girl-rose-city-girl-01-30ml',
    sku: 'AND-PG-001',
    name: 'Polygel -City Girl- Rose City Girl- (01) 30ml.',
    description: 'Polygel para construccion con tono comercial y presentacion de 30ml para uso profesional.',
    shortDescription: 'Polygel City Girl 30ml.',
    price: 7990,
    compareAtPrice: null,
    stock: 12,
    featured: true,
    badges: ['best-seller'],
    imageUrls: ['https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
    site: 'anahinails',
    subcategory: 'Construccion',
    brand: 'City Girl',
    variants: [],
  },
  {
    id: 'prod-04',
    slug: 'polygel-easy-gel-cover-pink-60g',
    sku: 'AND-PG-060',
    name: 'Polygel-Easy Gel -Cover Pink 60g.',
    description: 'Presentacion de 60g para servicio intensivo, ideal para mesa de trabajo con buena rotacion.',
    shortDescription: 'Polygel Easy Gel Cover Pink 60g.',
    price: 15600,
    compareAtPrice: null,
    stock: 18,
    featured: true,
    badges: ['new'],
    imageUrls: ['https://images.unsplash.com/photo-1607602132700-06825880252c?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-polygel',
    categoryName: 'Polygel',
    site: 'anahinails',
    subcategory: 'Easy Gel',
    brand: 'Easy Gel',
    variants: [],
  },
  {
    id: 'prod-05',
    slug: '2-marfil-cat-eye-city-girl-7-ml',
    sku: 'AND-CE-002',
    name: '2 MARFIL - CAT EYE CITY GIRL 7 ML.',
    description: 'Cat eye profesional con descuento activo y alta salida por tendencia y acabado visual.',
    shortDescription: 'Cat eye City Girl 7 ml en oferta.',
    price: 5350,
    compareAtPrice: 5700,
    stock: 8,
    featured: true,
    badges: ['sale', 'best-seller'],
    imageUrls: ['https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
    site: 'anahinails',
    subcategory: 'Cat Eye',
    brand: 'City Girl',
    variants: [],
  },
  {
    id: 'prod-06',
    slug: 'base-mineral',
    sku: 'AND-BM-010',
    name: 'Base Mineral',
    description: 'Base formulada con calcio, hierro y magnesio, ideal para unas debilitadas y servicio de cuidado.',
    shortDescription: 'Base fortalecedora vegana y cruelty free.',
    price: 14000,
    compareAtPrice: null,
    stock: 10,
    featured: false,
    badges: ['new'],
    imageUrls: ['https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
    site: 'anahinails',
    subcategory: 'Bases',
    brand: 'Bompassy',
    variants: [],
  },
  {
    id: 'prod-07',
    slug: 'kit-soft-gel-nude-studio',
    sku: 'AND-SG-007',
    name: 'Kit Soft Gel Nude Studio',
    description: 'Kit orientado a servicio rapido y prolijo para sets soft gel con terminacion comercial.',
    shortDescription: 'Kit integral de soft gel.',
    price: 26900,
    compareAtPrice: 29900,
    stock: 9,
    featured: false,
    badges: ['sale'],
    imageUrls: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-soft-gel',
    categoryName: 'Soft Gel',
    site: 'anahinails',
    subcategory: 'Kits',
    brand: 'Navi',
    variants: [],
  },
  {
    id: 'prod-08',
    slug: 'cabina-uv-led-diamond-x',
    sku: 'AND-CAB-008',
    name: 'Cabina UV LED Diamond X',
    description: 'Cabina profesional UV LED para servicio continuo en mesa de trabajo o salon.',
    shortDescription: 'Cabina profesional UV/LED.',
    price: 45900,
    compareAtPrice: 51900,
    stock: 8,
    featured: true,
    badges: ['sale'],
    imageUrls: ['https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-herramientas',
    categoryName: 'Cabinas y Herramientas',
    site: 'anahinails',
    subcategory: 'Cabinas',
    brand: 'Diamond',
    variants: [],
  },
  {
    id: 'prod-09',
    slug: 'alas-de-angel-1-dorado',
    sku: 'AND-DEC-009',
    name: 'Alas de Angel #1 Dorado',
    description: 'Aplique decorativo para sumar detalle y valor a trabajos de nail art y sets tematicos.',
    shortDescription: 'Aplique decorativo dorado.',
    price: 3990,
    compareAtPrice: null,
    stock: 50,
    featured: false,
    badges: ['new'],
    imageUrls: ['https://images.unsplash.com/photo-1583241801126-2b72975af370?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-decoracion',
    categoryName: 'Decoracion y Nail Art',
    site: 'anahinails',
    subcategory: 'Apliques',
    brand: 'Bompassy',
    variants: [],
  },
  {
    id: 'prod-ws-01',
    slug: 'buzo-wild-spirit-soul-club',
    sku: 'WS-BZ-001',
    name: 'Buzo Soul Club',
    description: 'Buzo premium a pedido con visual exclusiva y terminacion suave para usar todos los dias.',
    shortDescription: 'Buzo premium de diseño exclusivo.',
    price: 48900,
    compareAtPrice: null,
    stock: 18,
    featured: true,
    badges: ['best-seller'],
    imageUrls: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-ws-buzos',
    categoryName: 'Buzos',
    site: 'wildspirit',
    subcategory: 'Oversize',
    brand: 'Wild Spirit',
    variants: [
      {
        id: 'ws-bz-001-negro',
        name: 'Oversize Negro',
        color: 'Negro',
        imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
        stock: 6,
      },
      {
        id: 'ws-bz-001-arena',
        name: 'Oversize Arena',
        color: 'Arena',
        imageUrl: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
        stock: 5,
      },
    ],
  },
  {
    id: 'prod-ws-02',
    slug: 'remera-wild-spirit-essence-signature',
    sku: 'WS-RM-002',
    name: 'Remera Essence Signature',
    description: 'Remera de algodon premium hecha a pedido, pensada para identidad propia y uso diario.',
    shortDescription: 'Remera premium a pedido.',
    price: 28900,
    compareAtPrice: null,
    stock: 22,
    featured: true,
    badges: ['new'],
    imageUrls: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'],
    categoryId: 'cat-ws-remeras',
    categoryName: 'Remeras',
    site: 'wildspirit',
    subcategory: 'Boxy',
    brand: 'Wild Spirit',
    variants: [
      {
        id: 'ws-rm-002-blanco',
        name: 'Boxy Blanca',
        color: 'Blanco',
        imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
        stock: 10,
      },
      {
        id: 'ws-rm-002-stone',
        name: 'Boxy Stone',
        color: 'Stone',
        imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=80',
        stock: 12,
      },
    ],
  },
]
